# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# A target is a specification of a product from a pod.
target 'Runner' do
  # Flutter'ın pod'larını otomatik olarak bulmasını sağlar
  flutter_prebuild_pods

  # Uygulamanızdaki Flutter bağımlılıkları buraya eklenir
  # pod 'firebase_core' gibi

end
