# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

target 'Runner' do
  use_frameworks!
  
  # Pods for your Flutter application are defined below.
  # This simpler Podfile will work even if you don't have
  # any Flutter plugins that require native iOS code.
  
  # You can add your own pods here if needed.
  # For example: pod 'Firebase/Core', '~> 6.0'
end
